### ISSUE TITLE
Folder to Group Converter

### ISSUE THREAD

**Issue by gMagnus87** [veselcraft/progman#5]
I don't know if this project is still alive but I would like to suggest a tool that allows you to turn any folder into a group for PROGMAN.
When Windows 95 was born, Microsoft created an application called grpconv.exe that turned groups into folders for the Start Menu.

**Comment by veselcraft** [comment]
Sadly, i abandoned this project as i switched to Web development. But i may return to C# programming again, as i'll have more time and motivation :D
